spring:
  application:
    name: config
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8080/eureka/
       datasource:
         url: jdbc:mysql://111.230.169.249:3307/springcloud
         password: 123456
         username: root
         driver-class-name: com.mysql.jdbc.Driver
