spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://111.230.169.249:3307/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimeZone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 600000
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
#\u8BBE\u7F6E\u4E24\u4E2A\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u5F53\u5176\u4E2D\u4E00\u4E2A\u6CE8\u518C\u4E2D\u5FC3\u6302\u6389\u4E4B\u540E\uFF0C\u53E6\u4E00\u4E2A\u6CE8\u518C\u4E2D\u5FC3\u4F9D\u7136\u53EF\u7528
     defaultZone: http://localhost:8080/eureka/
#     defaultZone: http://localhost:8080/eureka/,http://localhost:8081/eureka/
#  instance:
#    hostname: productname
env:
 dkdk
